-d C:\Users\lickc\Desktop\Ic_wild\FPGA\somador 6 bits\impl\gwsynthesis\somador 6 bits.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\lickc\Desktop\Ic_wild\FPGA\somador 6 bits\src\somador.cst
-cfg C:\Users\lickc\Desktop\Ic_wild\FPGA\somador 6 bits\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
